### ISSUE TITLE
org.freedesktop.Sdk.Extension.shared-modules ?

### ISSUE THREAD

**Issue by eszlari** [flathub/shared-modules#101]
Maybe I'm missing something, but wouldn't it make sense to turn shared-modules into a SDK extension?

This would bring us:
1. shorter compile times
2. not having to mess with git modules (annoying with Github's web GUI)

**Comment by barthalion** [comment]
SDK extensions aren't supposed to be used as packages as seen in regular package managers.

**Comment by eszlari** [comment]
> SDK extensions aren't supposed to be used as packages as seen in regular package managers.

I think there's a misunderstanding.

Example: for Java apps you copy the JRE from the extension to `/app` with:
```
/usr/lib/sdk/openjdk11/install.sh
```

In this case, you would copy the modules you need:
```
/usr/lib/sdk/shared-modules/install-gtk2.sh
/usr/lib/sdk/shared-modules/install-python2.sh
```

**Comment by barthalion** [comment]
SDK extensions provide specific tools to build application for languages missing from SDK. `shared-modules` is just a way to reduce toil of writing new modules for something commonly used. We don't want it to be package dependencies and that's exactly what you're proposing here, one way or another. Applications should just bundle their dependencies.

There's a PR open to our actions repository which aims to automate bumping shared-modules in all Flathub automatically, it just needs some minor changes.

**Comment by eszlari** [comment]
> Applications should just bundle their dependencies.

This is exactly what I'm proposing?!

`install-foo.sh` would just include something like:
```
cp /usr/lib/sdk/shared-modules/foo/*.so /app/lib
cp /usr/lib/sdk/shared-modules/foo/*.h /app/include
```

**Comment by eszlari** [comment]
It also seems to me, that this makes the concept of `BaseAp` is redundant.

**Comment by TingPing** [comment]
The concept of BaseApp really shines when building things yourself is hard, like WebKit is a massive thing that takes hours to build sometimes. They have the big downside that you depend on another package keeping up with your needs.

Extension points shine for optional features you want to include in an application (or sdk).

shared-modules shine when you just want to reduce repetition.

**Comment by eszlari** [comment]
* SDK extensions are more flexible than a BaseApp, because you can add multiple extensions, while you can only choose one BaseApp.

* SDK extensions are more convenient than shared-modules, because they are pre-compiled and avoid git submodules. You also save CPU time for the Flathub CI.

**Comment by TingPing** [comment]
I believe your benefits are non-issues. Being binary is a downside as it means it has to grow an infinite list of branches for every runtime also.

**Comment by eszlari** [comment]
I know that these are not big issues (only the submodules thing really annoys me), just wanted some clarification.

Another thing, if you don't mind:

Don't you think, that is would have been possible, to turn all runtimes based on the freedesktop runtime into a runtime (+ SDK) extension of that runtime? e.g. org.freedesktop.Platform.gnome336 or org.freedesktop.Platform.kde514? Was this considered? Would there be important disadvantages to that? Apps that needed libraries form both, GNOME and KDE, are rare, but there are some that would benefit from that.

**Comment by TingPing** [comment]
> Apps that need libraries from both, GNOME and KDE, are rare

I think that is the *worst* benefit of that idea. What happens when they both provide the same libraries? Who wins? How can all combinations of all versions of different 'runtime extensions' even be sanely tested?

**Comment by eszlari** [comment]
> I think that is the worst benefit of that idea.

Of course, after gtk3 was moved into the freedesktop runtime, the problem is not that severe anymore.

On the other hand, apps having a variety of GUI toolkit dependencies is maybe not that rare after all, every audio app that utilizes LV2 has that problem: http://lists.lv2plug.in/pipermail/devel-lv2plug.in/2016-March/001593.html ("Luckily" a lot of them still use gtk2.)

> What happens when they both provide the same libraries? Who wins?

There is only one non-Qt/KDE module in the KDE runtime at the moment:
https://invent.kde.org/kde/flatpak-kde-runtime/-/blob/qt5.14/org.kde.Sdk.json.in

> How can all combinations of all versions of different 'runtime extensions' even be sanely tested?

Don't we have the same situation with `org.freedesktop.Platform.GL.default` today?

**Comment by TingPing** [comment]
> There is only one non-Qt/KDE module in the KDE runtime at the moment:

Ok that is honestly impressive and does minimize my concern but I don't think thats something to be relied upon.

The whole point of flatpak is to be simple. You want an app you get a blob of a runtime and a blob of an app. Sure some facts of reality complicated that but they are a compromise. Trying to turn the whole system into a traditional style package manger where you pick and choose binary libraries is counter to the goal.
