### ISSUE TITLE
Glew out of date (2.2.0 available)

### ISSUE THREAD

**Issue by ElXreno** [flathub/shared-modules#107]
Version [2.2.0 available](https://sourceforge.net/projects/glew/files/glew/2.2.0/) (created 2020-03-16). Currently in manifest used 2.1.0 version which was created 2017-07-31.
It might be worth it to upgrade?

**Comment by bilelmoussaoui** [comment]
Merge requests are welcome :)

**Comment by ElXreno** [comment]
@bilelmoussaoui no problem :)
https://github.com/flathub/shared-modules/pull/109
