### ISSUE TITLE
Lua 5.3 updates break org.videolan.VLC

### ISSUE THREAD

**Issue by A6GibKm** [flathub/shared-modules#116]
See https://github.com/flathub/org.videolan.VLC/pull/111. The changes introduced are https://github.com/flathub/shared-modules/compare/d6455cb..66c9eff#diff-da898bf556886005e6fb5da79432b74b.

**Comment by TingPing** [comment]
CC @Unrud 

`luaL_checkint` is deprecated in 5.3.
