### ISSUE TITLE
Add Qt5 and PyQt5

### ISSUE THREAD

**Issue by darkdragon-001** [flathub/shared-modules#119]
This is used in a vast number of packages. Would be a lot easier to maintain it only once.

**Comment by Lctrs** [comment]
- `Qt5`: just use `org.kde.Platform`
- `PyQt5`: not really realistic IMHO. Most apps will want to enable only the modules they need to reduce build time/install size, but if you really want to, a good starting point could be what we did in [`org.musicbrainz.Picard`](https://github.com/flathub/org.musicbrainz.Picard/blob/master/org.musicbrainz.Picard.json#L36-L156). We successfully build `PyQt5` using `SIP5`.
