### ISSUE TITLE
Add TCL as shared library

### ISSUE THREAD

**Issue by SISheogorath** [flathub/shared-modules#141]
I just tried to re-work the TCL module in the Element flatpak using https://github.com/flathub/im.riot.Riot/pull/187

Since I remember that originally the TCL module was just copied from some other sqlcipher user, I though it might be worth to check whether one wants to create it as a shared library:

https://github.com/flathub/edu.stanford.Almond/blob/96a338a6196673e8e34093cf5d7dcb3e39d64b3c/edu.stanford.Almond.json#L219-L234
https://github.com/flathub/cc.retroshare.retroshare-gui/blob/f04704b9677b815b546ea4edef349c7e1b4a8785/cc.retroshare.retroshare-gui.yaml#L31-L41
https://github.com/flathub/org.openmsx.openMSX/blob/d550ba3e2088c3141025ff5f285c7fa4774f9040/org.openmsx.openMSX.yaml#L31-L42
https://github.com/flathub/org.kde.skrooge/blob/7ae18045b2aca325517cf2bf23ec6694e1be250e/org.kde.skrooge.json#L31-L48
https://github.com/flathub/io.github.qtox.qTox/blob/132b9dd57c95b04602c4893042462d94284c6ac8/io.github.qtox.qTox.json#L42-L56
https://github.com/flathub/com.gitlab.guillermop.MasterKey/blob/33603d9836dcaae008e920026bdecf2001b3597e/com.gitlab.guillermop.MasterKey.json#L25-L45
https://github.com/flathub/im.riot.Riot/blob/644f94ae656ef25518a7d48cf9b78210b7d009f9/im.riot.Riot.yaml#L54-L63

Given the amount of applications that use TCL at least as part of their built process, I think we could consider unify the efforts, as it's also not updated in any meaningful way in most of those applications.

**Comment by bbhtt** [comment]
TCL is in the runtime from 24.08:

```
$ flatpak run --command=find org.freedesktop.Platform//24.08 /usr/lib -name libtcl*.so

/usr/lib/tcl8.6/sqlite3/libtclsqlite3.so
/usr/lib/x86_64-linux-gnu/libtcl8.6.so
```
