### ISSUE TITLE
[libappindicator] SVG icon not supported: GdkPixbuf.PixbufError

### ISSUE THREAD

**Issue by proninyaroslav** [flathub/shared-modules#148]
I'm getting this error when using `libappindicator`, compiled from shared modules: 

`libretrack, Impossible to read image info from path '/app/libretrack/data/icons/app-icon.svg': GdkPixbuf.PixbufError: Failed to recognize image format`

when building with normal Ubuntu or Fedora dependencies (without using Flatpak) everything works perfectly and the indicator show SVG icon.

**Comment by proninyaroslav** [comment]
Sorry, this is the`gnome-shell-extension-appindicator` extension bug.

**Comment by TingPing** [comment]
Its not a bug in the extension. The application can only use icons by name not by path when sandboxed.
