### ISSUE TITLE
WxWidgets seems to be used a lot

### ISSUE THREAD

**Issue by Kirtai** [flathub/shared-modules#157]
I've noticed that quite a few flatpaks use WxWidgets, each with their own custom build rules. Would it be worth adding it to the shared modules?

**Comment by Kirtai** [comment]
Some I've found are

https://github.com/flathub/net.mancubus.SLADE
https://github.com/flathub/com.bixense.PasswordCalculator
https://github.com/flathub/br.gov.cti.invesalius
https://github.com/flathub/net.mediaarea.MediaInfo
https://github.com/flathub/net.pcsx2.PCSX2
https://github.com/flathub/com.play0ad.zeroad
https://github.com/flathub/org.aliflang.lang
https://github.com/flathub/net.sourceforge.Hugin
https://github.com/flathub/edu.berkeley.BOINC
https://github.com/flathub/org.codeblocks.codeblocks
https://github.com/flathub/org.opencpn.OpenCPN
https://github.com/flathub/org.kicad.KiCad

**Comment by TingPing** [comment]
One problem is WxWidgets has a ton of build-time customization options. I think there is some value in projects doing the most minimal builds they need.

**Comment by hfiguiere** [comment]
and some projects like Audacity use their own fork.... (which is used in the flatpak)

**Comment by Eonfge** [comment]
@TingPing Is totally right sadly. SLADE which I maintain doesn't even support the latest WxWidgets, but it does require OpenGL rendering.

**Comment by Mailaender** [comment]
Same language wrappers like wxLua also work only with specified version of wxWidgets. While it is a pain to build, I also don't see a common denominator.

**Comment by orowith2os** [comment]
WxWidgets is weird enough that one build config, even version, that's used by one app might not work with another - I think that makes this issue nonsolvable as a shared module. It'll still end up duplicated by other apps. 

I'll close this as not planned, but feel free to reopen if you feel you can put this to use.
