### ISSUE TITLE
git-init can cause process to fail if gpg signing set to true as global option

### ISSUE THREAD

**Issue by cobratbq** [flathub/shared-modules#165]
In case of [libcanberra](<https://github.com/flathub/shared-modules/blob/068f80b296f73d7d6eb2aee4fa01f9907d34daa8/libcanberra/libcanberra.json#L27>), a `git init` is performed due to a necessary action of applying a patch. If _git_ is configured _globally_ to require gpg signing (`commit.gpgsign` `true`) then `git init` will fail expecting a certain key to be available and useable at that moment.

**Comment by TingPing** [comment]
Patches welcomed to convert that patch into one not relying upon git.

**Comment by cobratbq** [comment]
@TingPing Here's a patch. According to manpage of patch, heading and trailing crap is ignored, so the content at the start is not an issue. This change works for me.

I cannot attach the patch as a file. The content and/or file extension is not allowed.
```patch
diff --git a/libcanberra/libcanberra.json b/libcanberra/libcanberra.json
index ac44194..9dbb637 100644
--- a/libcanberra/libcanberra.json
+++ b/libcanberra/libcanberra.json
@@ -23,13 +23,11 @@
         {
             "type": "archive",
             "url": "http://0pointer.de/lennart/projects/libcanberra/libcanberra-0.30.tar.xz",
-            "sha256": "c2b671e67e0c288a69fc33dc1b6f1b534d07882c2aceed37004bf48c601afa72",
-            "git-init" : true
+            "sha256": "c2b671e67e0c288a69fc33dc1b6f1b534d07882c2aceed37004bf48c601afa72"
         },
         {
             "type": "patch",
-            "path": "0001-gtk-Don-t-assume-all-GdkDisplays-are-GdkX11Displays-.patch",
-            "use-git-am": true
+            "path": "0001-gtk-Don-t-assume-all-GdkDisplays-are-GdkX11Displays-.patch"
         }
     ]
 }
```

**Comment by hfiguiere** [comment]
> I cannot attach the patch as a file. The content and/or file extension is not allowed.

But you can submit a Pull Request. That would be much appreciated.
