### ISSUE TITLE
issues with the latest version of libsecret

### ISSUE THREAD

**Issue by mijorus** [flathub/shared-modules#195]
Hi,
I have noticed some issues using the latest version of `libsecret` available in the shared-modules.

Specifically, [Mongo Compass](https://github.com/flathub/flathub/pull/3269#issuecomment-1164439700) was not storing passwords correctly util I downgraded manually to 0.19.1. This issue was also reported by others https://github.com/flathub/com.microsoft.Teams/commit/74040c479beaf325f7b7c95210c74ba90d7d3026

Unfortunately I couldn't get any meaningful log about the issue.

**Comment by A6GibKm** [comment]
This issue is not directly related to how it is packaged in shared-modules. See https://gitlab.gnome.org/GNOME/libsecret/-/issues/49.

**Comment by mijorus** [comment]
> This issue is not directly related to how it is packaged in shared-modules. See https://gitlab.gnome.org/GNOME/libsecret/-/issues/49.

Thanks, I'm closing this

**Comment by Erick555** [comment]
> This issue is not directly related to how it is packaged in shared-modules

I think some action should be taken though as it's long standing issue that discourages apps to use shared-modules. The `-Dgcrypt=false` sounds like least invasive workaround.

**Comment by A6GibKm** [comment]
No, I am not in favor of disabling `gcrypt` here as it is working and doing what was intended to do for a ton of apps. Its just a handful of apps for which it fails and those can very well build its own libsecret.
