### ISSUE TITLE
SDL/sdl12-compat.json has an undeclared dependency on on glu/glu-9.json

### ISSUE THREAD

**Issue by ssokolow** [flathub/shared-modules#202]
Currently, `SDL/sdl12-compat.json` fails to build unless I manually add `glu/glu-9.json` before it in the build process.

**Comment by TingPing** [comment]
If you could open a PR for a modified version that works it would be appreciated.

I believe you just need to add a `"modules": [ "../glu/glu-9.json" ]` in there.
