### ISSUE TITLE
Fluidsynth 2.2.0 SOVERSION bump

### ISSUE THREAD

**Issue by Zumorica** [flathub/shared-modules#211]
Fluidsynth version 2.2.0 introduced some [breaking changes](https://www.fluidsynth.org/api/RecentChanges.html#NewIn2_2_0) and bumped Fluidsynth's SOVERSION from 2 to 3.
For backwards compatibility purposes, it might be a good idea to rename the current fluidsynth modules to `fluidsynth3.json` and so on and create a new `fluidsynth2.json` module that specifies version 2.1.9 (the latest fluidsynth version with SOVERSION 2)

The reason I'm opening this issue is because I'm trying to create a flatpak for a program but it depends on `libfluidsynth.so.2`, whereas the current `fluidsynth2.json` module in this repo builds and creates `libfluidsynth.so.3` instead.

**Comment by hfiguiere** [comment]
> The reason I'm opening this issue is because I'm trying to create a flatpak for a program but it depends on `libfluidsynth.so.2`, whereas the current `fluidsynth2.json` module in this repo builds and creates `libfluidsynth.so.3` instead.

Are you repacking a binary? Otherwise it shouldn't matter. I'd recommend that you don't use the shared-module in that case.

**Comment by Zumorica** [comment]
> Are you repacking a binary? Otherwise it shouldn't matter. I'd recommend that you don't use the shared-module in that case.

Yes. Fluidsynth 2.1.X is not ABI compatible with Fluidsynth 2.2+ but I guess I'll just not use shared-modules, as you suggested.

**Comment by hfiguiere** [comment]
building from source is to avoid ABI issues. It's the whole point.
