### ISSUE TITLE
SDL2 submodule, with libdecor

### ISSUE THREAD

**Issue by orowith2os** [flathub/shared-modules#217]
SDL2 seems to have gotten one of its final releases, and the SDL team is doing some major cleanup for SDL3.

I believe it would be beneficial to add an SDL2 submodule that functions similarly to the original SDL submodule(s).

Is there anything I should add alongside a basic SDL2 and libdecor submodule? How it should be structured might be concerning too, should I have them both be in the same folder (GIT_ROOT/SDL2/{sdl2.json, libdecor.json}. sdl2.json pulls in libdecor.json during build) or separate submodules?

**Comment by TingPing** [comment]
I would have "sdl2.json" implicitly pull in "libdecor.json" at all times so users of this never need to think about it.

They can be in their own folders so people can individually use libdecor if they wish.

Make sure you update `CODEOWNERS` with somebody to maintain these modules.

**Comment by orowith2os** [comment]
@TingPing So, in a separate MR, add sdl2 and then link back to this libdecor submodule using ../libdecor/libdecor-ver.json?

**Comment by TingPing** [comment]
Yup.

**Comment by orowith2os** [comment]
> @orowith2os Actually I'm a bit confused, `sdl2` is inside the freedesktop-sdk. Have you tried getting `libdecor` added there as well?

It was discussed a while back, but denied. And just building libdecor inside of flatpak doesn't allow the runtime SDL2 to use that either, so that's my main motivation.

One moment, I'll see if I can drag up the exact issue...

**Comment by TingPing** [comment]
OK. It is fine to keep here for a bit. The ultimate goal next year should be a push to get it into fdo though IMO.

**Comment by orowith2os** [comment]
I would like to do that, yes, though at that point, I'd prefer it that the people there manage it; I don't like using gitlab for interacting with other users.

**Comment by orowith2os** [comment]
Opting to exclude linking to libdecor in the SDL2 manifest, otherwise managing it and other, alternative, SDL2 manifests might serve to be a pain.
