### ISSUE TITLE
VLC interface way too big.

### ISSUE THREAD

**Issue by brlbil** [flathub/shared-modules#23]
VLC interface way too big, icons and text resolution is low.

I have NVidia and Intel grahpics cards, on my laptop,
I have no this has anything to do with them.

org.freedesktop.Platform.GL.nvidia-390-48/x86_64/1.4
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6

I have installed other applications an they  work fine.

![vlc](https://user-images.githubusercontent.com/3773321/42424791-d608c1fa-831a-11e8-973f-ec183b886dcd.png)

**Comment by barthalion** [comment]
Can you report it against VLC flathub repository? This one is for shared-modules, not particular apps.
