### ISSUE TITLE
Shared module request: libnotify

### ISSUE THREAD

**Issue by Mikaela** [flathub/shared-modules#234]
While libnotify is part of `org.gnome.Platform`, I am seeing many `org.freedesktop.Platform` using flatpaks include it manually and I think it would be a good candidate for shared-modules.

[I asked about this on Matrix and was encouraged to open an issue here](https://matrix.to/#/%23flatpak%3Amatrix.org/%24ftzwQp8CurbQLgb07P0JWyKtsOCx6hNhm7njdOgapRA?via=pikaviestin.fi&via=matrix.org&via=knot.im&via=envs.net).

**Comment by A6GibKm** [comment]
I think there are about 27 modules using it. I think this is a reasonable proposal for a shared-module but the hard part is having someone do the PR,  maintain  it for the foreseeable future, and open ~27 MRs to modules to projects building it manually.

Regarding the last point, from 0.8 libnotify onwards it uses the notification portal so one should remove the `--talk-name=org.freedesktop.Notifications` permissions.

**Comment by orowith2os** [comment]
Why not add it to the freedesktop runtime instead?

**Comment by A6GibKm** [comment]
And some apps do not even work with the regular install, protonmail-bridge requires either an old version or to disable the gcrypt option to work. Other apps had similar problems.

**Comment by Erick555** [comment]
What gcrypt has to do with libnotify?

**Comment by A6GibKm** [comment]
I am sorry, I was just in a convo about libsecret and I mixed the two of them in my mind.

Regarding the discussion, I have seen very little use of libnotify outside of GNOME to be honest, and it GNOME it makes no sense to use it anyways.

**Comment by bbhtt** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1642 If it doesn't get included in runtime I'll add it to shared-modules and handles reaching out to the ~30-33 apps using it.

**Comment by nanonyme** [comment]
I would note that 23.08 is already out and the request to include it into runtime is already months late.

**Comment by bbhtt** [comment]
It was added to the SDK/runtime. If everything goes well, it'll be in 24.08 I think.
