### ISSUE TITLE
Request to downgrade libsecret to v0.19.1

### ISSUE THREAD

**Issue by mhoeher** [flathub/shared-modules#254]
Hi guys,

In the past, I noticed issues with my app when loading secrets - while saving (and deleting) them seemed to work quite fine, it failed to load the secrets at app startup. I observed that the issue got mitigated a bit by adding a delay at the startup (i.e. wait for 3-5s before attempting to load secrets).

I have to say I don't use libsecret directly but via qtkeychain.

Recently, a user reported the same issue again, see https://gitlab.com/rpdev/opentodolist/-/issues/635

I did some research, even raising an issue against qtkeychain before stumbling across several issues in libsecret's bug tracker: 

https://gitlab.gnome.org/GNOME/libsecret/-/issues/?sort=created_date&state=opened&search=flatpak&first_page_size=20

In my app, I was using libsecret from the shared modules. I first attempted an upgrade, but this didn't help. I then went back to the version of libsecret I used before switching to the shared modules (which was 0.19.1) and - voila - the app started to work again as expected!

I also found #195, but I find it a bit inconclusive. From my perspective, the best way would be to downgrade to 0.19.1 for the time being, as it seems any later version is either unusable with Flatpak or requires a workaround (disabling the file based storage) which - from my understanding - shall be the default all Flatpak apps align on (correct me if I'm wrong here). IMAO, the shared modules should provide working software modules (not only for "most" apps, but all).

If you decide to reject this issue/request (which, given some of the arguments in the other ticket, I can fully understand) I would at least ask you to stop promoting use of the shared modules for libsecret for new projects or make the app owners aware of this bug. In my case, the change to shared modules was proposed to me and I opted to follow that PR (see https://github.com/flathub/net.rpdev.OpenTodoList/pull/10), not knowing that it contained such an "easter egg".

As a side note, please also bear in mind that any app which uses qtkeychain for storing its secrets most likely will be affected.

Thanks for considering!

**Comment by orowith2os** [comment]
As @A6GibKm said in the previous issue:

> No, I am not in favor of disabling gcrypt here as it is working and doing what was intended to do for a ton of apps. Its just a handful of apps for which it fails and those can very well build its own libsecret.

If it doesn't work for you, as some shared modules may, ship it on your own with your required version and features.

And as for this:

> as it seems any later version is either unusable with Flatpak or requires a workaround (disabling the file based storage) which - from my understanding - shall be the default all Flatpak apps align on (correct me if I'm wrong here)

What is this about file-based storage? Why can't it be used in Flatpak? They have their private directories, which other apps can't access.

**Comment by TingPing** [comment]
If you give your app access to `org.freedesktop.secrets` it bypasses the flatpak specific behavior.

**Comment by TingPing** [comment]
Hmm it seems the app already has it.. maybe that is what changed. Will have to look at their codebase.

**Comment by mhoeher** [comment]
> What is this about file-based storage? Why can't it be used in Flatpak? They have their private directories, which other apps can't access.

IIRC, the preferred way in Flatpak to store secrets is to store them encrypted in a file within the private data folder of each app (vs. accessing the host's secret service via D-Bus). If I understood correctly, this is the storage method that fails in this case? Anyway, I'm not too familiar with this topic - in the end, I'm just a user of qtkeychain which - in my case - fails with recent libsecret versions.

> If you give your app access to org.freedesktop.secrets it bypasses the flatpak specific behavior.

Yes, I think I tried this some months back when I first tried to debug the issue. Unfortunately, it didn't change anything.

What I find interesting is that the issue seems to sometimes not occur if some delay is added before trying to load secrets. 

> Hmm it seems the app already has it.. maybe that is what changed. Will have to look at their codebase.

Let me know if you need any help/directions when checking the code or debugging. I can als add some debug output if this helps. Cause... I know I can downgrade (and I did, to enable my users), but I'd prefer shipping up to date dependencies 😉

**Comment by orowith2os** [comment]
> Anyway, I'm not too familiar with this topic - in the end, I'm just a user of qtkeychain which - in my case - fails with recent libsecret versions.

You should get in touch with those developers to ask them to bundle it manually.
