### ISSUE TITLE
Include GCR

### ISSUE THREAD

**Issue by x80486** [flathub/shared-modules#283]
Would it be possible to add `GCR` to the shared modules? Currently there are a few applications (e.g.: [DataGrip](https://github.com/flathub/com.jetbrains.DataGrip/blob/master/com.jetbrains.DataGrip.yaml#L27), [IntelliJ IDEA Community](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/blob/master/com.jetbrains.IntelliJ-IDEA-Community.yaml#L28), [IntelliJ IDEA Ultimate](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/blob/master/com.jetbrains.IntelliJ-IDEA-Ultimate.yaml#L30), and [SmartGit](https://github.com/flathub/com.syntevo.SmartGit/blob/master/com.syntevo.SmartGit.yaml#L23)) using it, so I think it's better to externalize it here as a module.

**Comment by TingPing** [comment]
One of those uses gcr 4 and the others gcr 3. Seems pretty limited and its very possible other projects will want different build options like introspection enabled.

**Comment by x80486** [comment]
The reason for the different versions is because I haven't been able to build `GCR 4.x` on `FreeDesktop` :grimacing:

Regardless, it could probably work with a set of standard options that most projects will use. I see some modules are configured in such way.
