### ISSUE TITLE
udev having problems building

### ISSUE THREAD

**Issue by Othko97** [flathub/shared-modules#30]
udev doesn't build using flatpak-builder 1.0.0 on aarch64, against freedesktop-sdk 18.08. It seems to try to strip binaries in .flatpak-builder/, but I'm unfamiliar with how flatpak-builder works, so I'm unsure if this behaviour is expected or not.

Relevant build log:
```
compressing debuginfo in: /home/nvidia/net.sourceforge.ExtremeTuxRacer/.flatpak-builder/rofiles/rofiles-cwr7Kt/files/libexec/udevd
Warning: eu-elfcompress not installed, will not compress debuginfo
stripping /home/nvidia/net.sourceforge.ExtremeTuxRacer/.flatpak-builder/rofiles/rofiles-cwr7Kt/files/libexec/udevd to /home/nvidia/net.sourceforge.ExtremeTuxRacer/.flatpak-builder/rofiles/rofiles-cwr7Kt/files/lib/debug/libexec/udevd.debug
Error: module udev: Failed to execute child process "eu-strip" (No such file or directory)
```

**Comment by TingPing** [comment]
> eu-elfcompress

Sounds like a missing tool on the host.

**Comment by jurf** [comment]
Is this Ubuntu? But yeah, saw this before, but I forget what the package is called. Thought this dependency problem was long resolved though…

**Comment by barthalion** [comment]
Yeah, it's a packaging bug, elfutils should be a dependency of flatpak-builder (and it is on Arch and Fedora).
