### ISSUE TITLE
Please update Fluidsynth v2.3.5 

### ISSUE THREAD

**Issue by pedrolcl** [flathub/shared-modules#300]
[Fluidsynth v2.3.5](https://github.com/FluidSynth/fluidsynth/releases/tag/v2.3.5) was released on Mar 28, 2024.

A pull request  #299 is available, that has been opened on April 4, 2024.

**Comment by bbhtt** [comment]
The owner of the module is travelling. You'll have to wait to get a review.

**Comment by pedrolcl** [comment]
> The owner of the module is travelling. You'll have to wait to get a review.

Well,  @hfiguiere has reviewed today some PRs,  (flathub/pull/5157 , flathub/pull/5151) and more the past two weeks.

Anyway,  what may be so difficult to review in this PR? The sha256 hash? 

https://www.virustotal.com/gui/url/0fcff4c2f3baae98da9ed64d697680481c11ee8e166b54ea72fc396a2b396b38/details
https://www.virustotal.com/gui/file/f89e8e983ecfb4a5b4f5d8c2b9157ed18d15ed2e36246fa782f18abaea550e0d?nocache=1

**Comment by bbhtt** [comment]
No, the PR is fine. People are volunteers here. If someone hasn't reviewed it, it means they are busy.

**Comment by hfiguiere** [comment]
yeah some people are busy making a living and here isn't making a living. So please have patience. What are the changes that make it so urgent that 9 days is too long?
