### ISSUE TITLE
Why squashfs-tools no zstd support ?

### ISSUE THREAD

**Issue by Boria138** [flathub/shared-modules#345]

**Comment by hfiguiere** [comment]
issue description is empty

**Comment by Boria138** [comment]
As I asked in the title, why squashfs-tools is built without ZSTD_SUPPORT, mksquashfs -comp zstd doesn't work without it, also GZIP_SUPPORT=1 LZ4_SUPPORT=1 LZMA_XZ_SUPPORT=1 XATTR_SUPPORT=1 is missing, I would add gzip and zstd as the most popular compression methods to the already existing lzo and xz ones

**Comment by bbhtt** [comment]
You can open a PR it is missing because no one added it.
