### ISSUE TITLE
libayatana-libappindicator looks different on flatpak

### ISSUE THREAD

**Issue by sblantipodi** [flathub/shared-modules#352]
Hi, there,
I'm using libayatana-libappindicator.

do you have any idea why if I run it native it looks like this:
![388680674-a58078dc-2cee-4d88-9ced-55222fecf1a9](https://github.com/user-attachments/assets/dd259114-117f-48ee-8429-9f2d67408c65)

and if I run it via flatpak it looks like this?
![388680934-6b022018-ced3-45f6-bac2-35d090033a8e](https://github.com/user-attachments/assets/e3a84613-266d-4ef2-ad1c-45a22bc18eb4)

**Comment by bbhtt** [comment]
Because you are missing the dark version of whatever theme you have installed on the host probably Yaru-dark.

It's not an issue with the appindicator build recipe.

**Comment by TingPing** [comment]
Appindicators do not render with a GTK theme, only the fallback GtkStatusIcon.

So it is some dbus issue.

**Comment by bbhtt** [comment]
In that case you can probably find the permission needed using `flatpak run --log-session-bus $appid`
