### ISSUE TITLE
udev build fails with freedesktop 18.08

### ISSUE THREAD

**Issue by BeagleJoe** [flathub/shared-modules#43]
The udev shared-module fails to build with  org.freedesktop.Platform 18.08
Works with org.freedesktop.Platform 1.6 (also works with kde and gnome)
Flatpak version 1.2.3
Flatpak-builder version 1.05
This also affects the build bot.

``
/usr/bin/install: cannot create regular file '/usr/lib/systemd/system/udev-control.socket': Read-only file system
/usr/bin/install: cannot create regular file '/usr/lib/systemd/system/udev-kernel.socket': Read-only file system
/usr/bin/install: cannot create regular file '/usr/lib/systemd/system/udev.service': Read-only file system
/usr/bin/install: cannot create regular file '/usr/lib/systemd/system/udev-trigger.service': Read-only file system
/usr/bin/install: cannot create regular file '/usr/lib/systemd/system/udev-settle.service': Read-only file system
make[3]: *** [Makefile:2534: install-systemdsystemunitDATA] Error 1
make[2]: *** [Makefile:3109: install-am] Error 2
make[1]: *** [Makefile:2624: install-recursive] Error 1
make: *** [Makefile:3103: install] Error 2
``

A simple test project:
[a.test.project.yaml.txt](https://github.com/flathub/shared-modules/files/2933471/a.test.project.yaml.txt)

**Comment by Pixelnarium** [comment]
Same problem. I don't know what broke it but I think it needs some value for "--with-systemdsystemunitdir=DIR"? i.e. --with-systemdsystemunitdir=/app/lib/systemd? Maybe @TingPing knows more?

**Comment by TingPing** [comment]
@Pixelnarium 	Sounds right if you want to test it and submit a PR. (That file is unused anyway so it will also be added to `cleanup`)

**Comment by Pixelnarium** [comment]
Done. As I said in the pull request, I can't test it since it never worked for me.

**Comment by superm1** [comment]
It looks like it's causing problems for fwupd flatpak too, thanks for filing that PR.

**Comment by hughsie** [comment]
Do we have any ideas on how to reproduce the failure? I'd be happy to verify the PR if I had some way of reproducing it :)

**Comment by Pixelnarium** [comment]
Is your 18.08 Sdk up-to-date? There seems to be a new file <sdkpath>/files/share/pkgconfig/systemd.pc and udev finds this and tries to put files in theses pathes too.

**Comment by TingPing** [comment]
I'll just assume its fixed, is a trivial change.

**Comment by hughsie** [comment]
It fixed fwupd CI, so thanks!

**Comment by TingPing** [comment]
Somebody else mentioned `--without-systemdsystemunitdir` is also valid since we don't use the unit.
