### ISSUE TITLE
Deprecate lame in favour of org.freedesktop.Platform.GStreamer.mp3?

### ISSUE THREAD

**Issue by jakobjakobson18** [flathub/shared-modules#55]
Hi there,

`org.freedesktop.Platform.GStreamer.mp3` provides a mp3 encode/decoder and it's mantained by freedesktop. So is there any special need to share `lame` via the shared-modules?

Regards

**Comment by TingPing** [comment]
Thats probably a discussion to have with the projects using it. Maybe they explicitly depend on lame, maybe lame is better, etc.

**Comment by Erick555** [comment]
```
$ flatpak remote-info flathub org.freedesktop.Platform.GStreamer.mp3
error: Error searching remote flathub: Can't find ref org.freedesktop.Platform.GStreamer.mp3
```

Where I can find such thing?

**Comment by jakobjakobson18** [comment]
Well, I found it on the following page: [Flatpak wiki](https://github.com/flatpak/flatpak/wiki/Extensions)
But to be honest, I never checked myself if it's (still) working.

**Comment by jakobjakobson18** [comment]
The [Steam manifest](https://github.com/flathub/com.valvesoftware.Steam/blob/master/com.valvesoftware.Steam.yml) uses such extensions.

**Comment by Erick555** [comment]
It uses other extensions but not `org.freedesktop.Platform.GStreamer.mp3`. I think it doesn't exist anymore and wiki is juts outdated.

**Comment by jakobjakobson18** [comment]
Okay, then I'll close it.

**Comment by TingPing** [comment]
mp3 decoder is in the main runtime because the patent expired.
