### ISSUE TITLE
[QUESTION] Why didn't shared-modules merge modules from casept/flatpak-modules?

### ISSUE THREAD

**Issue by user5145** [flathub/shared-modules#75]
1. Is there any difference between shared-modules and casept/flatpak-modules. 
2. Why didn't shared-modules merge modules from casept/flatpak-modules?
3. Is the goal of shared-modules to keep every modern library that's not included in freedesktop.Platform if not then why?

**Comment by Erick555** [comment]
What is casept/flatpak-modules?

**Comment by user5145** [comment]
it's a project that i found on github. It seems to serve the same purpose as flathub/shared-modules

**Comment by Erick555** [comment]
I see however it looks abandoned. Anyway flathub/shared-modules is collaborative project and if you have something useful to add here feel free to open PR.

**Comment by user5145** [comment]
ok thanks. I thought that it's limited to a few libraries that were selected as important.

**Comment by Erick555** [comment]
I'm not the one who decides about what is allowed here but I think the requirement is that new module can be used by multiple apps in flathub.

**Comment by user5145** [comment]
to sum it up i will try to answer my own questions. please correct me if i'm wrong
1. no
2. becasue flatpak-modules is abandoned and not well known
3. your last comment answers it
