### ISSUE TITLE
QT4 doesn't compile with runtime 19.08

### ISSUE THREAD

**Issue by Unrud** [flathub/shared-modules#81]
https://flathub.org/builds/#/builders/35/builds/1216

**Comment by linuxrider** [comment]
an issue regarding gcc9 is preventing successful compilation of qt4:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925811

**Comment by Unrud** [comment]
Was fixed in https://github.com/flathub/shared-modules/commit/eec5f48cc90051c4c99c6c9464d55f171035b042.
