### ISSUE TITLE
Auto bump the shared-modules for sensitive ones

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/shared-modules#92]
Shared-modules contains some of the sensitive modules. So far, updating the module here with the latest security patches isn't enough as the apps have to update their shared-modules submodule and re-build the app with it.

We can setup a Github action that creates a merge request automatically for each app that uses it on Flathub. This will make it easier for app maintainers too :)

**Comment by bochecha** [comment]
> We can setup a Github action that creates a merge request automatically for each app that uses it on Flathub. This will make it easier for app maintainers too :)

Yes.

I know this isn't what you're suggesting but I'd rather make it explicit: let's **not** make it automatically merge anything though (even on successful builds) so that app maintainers have a chance to test the resulting builds. (whether they actually do it though is not the point)

**Comment by bilelmoussaoui** [comment]
We can follow what flatpak-external-data-checker does in https://github.com/flathub/flatpak-external-data-checker/pull/55

**Comment by dreua** [comment]
Whats the status here? I'd welcome such a solution since I now have almost all dependencies automatically checked and updated by external-data-checker via PR. Just the one dependency (intltool) from shared-modules needs to be manually checked and updated.
Is there an easy solution to get notified when shared-modules gets updated?

**Comment by TingPing** [comment]
`intltool` hasn't been developed since 2015 so that isn't a worry.

This task probably needs a good amount of work to set up CI to auto build/update everything.

**Comment by bbhtt** [comment]
Fixed via https://github.com/flathub/shared-modules/pull/250
